### ISSUE TITLE
Messages that are outside of the convention

### ISSUE THREAD

**Issue by incebellipipo** [uri-ocean-robotics/mvp_msgs#8]
These messages must be changed to my opinion:
- https://github.com/uri-ocean-robotics/mvp_msgs/blob/noetic-devel/msg/VehicleStatus.msg 
  **Time message must be changed**
- https://github.com/uri-ocean-robotics/mvp_msgs/blob/noetic-devel/msg/ModemPose.msg 
  **Position should be a geometry_msgs** type and should not include LAT LONG. **LAT-LONG should be a separate topic.**
- https://github.com/uri-ocean-robotics/mvp_msgs/blob/noetic-devel/msg/ModemHealth.msg 
  This should have a documentation on it. And, if it can be represented with other available message types, it should be removed. Example: [mvp_msgs/Float64Stamped](https://github.com/uri-ocean-robotics/mvp_msgs/blob/noetic-devel/msg/Float64Stamped.msg)

Most importantly, the quality of the newly added messages are poor. In addition to that, it seems like it is getting special to ALPHA family of vehicles. MVP designed as a framework to fit for most of the vehicles. If there is any specific things going on, you guys should not place it into mvp_msgs.

We should be discussing it further.

**Comment by incebellipipo** [comment]
_These are mostly opinions based on initial design considerations:_

Some messages should considered removal or migration. These are
- https://github.com/uri-ocean-robotics/mvp_msgs/blob/noetic-devel/msg/DVL.msg
- https://github.com/uri-ocean-robotics/mvp_msgs/blob/noetic-devel/msg/DVLBeam.msg
- https://github.com/uri-ocean-robotics/mvp_msgs/blob/noetic-devel/msg/MSISInfo.msg
- https://github.com/uri-ocean-robotics/mvp_msgs/blob/noetic-devel/msg/ModemHealth.msg
- https://github.com/uri-ocean-robotics/mvp_msgs/blob/noetic-devel/msg/ModemPose.msg

Additional notes:
- For ModelHealth and ModelPose messages: If these message types are designed with considering other products in the market _and_ if it is considered that there will be a package called `mvp_usbl`, than they may stay.
- About sensors in general: If there is no plan for new mvp program for specific for processing sensor information, there shall not be a sensor msgs description in mvp_msgs.

**Comment by linzha0** [comment]
removed all the sensor messages. will close this issue. we can re-open it if future modifications are needed!
